### ISSUE TITLE
这个库在三大平台上有经过充分的测试吗?

### ISSUE THREAD

**Issue by textGamex** [NeverMorewd/Hosting.Avaloniaui#2]

**Comment by textGamex** [comment]
另外, AddAvaloniauiDesktopApplication方法必须在非Main方法中调用吗?

**Comment by NeverMorewd** [comment]
不是、可以在直接在main里调用。

以下系统验证过：
window10、window11、wls-Ubuntu20.04
本仓库是基于Hosting和Avaloniaui开发的，没有平台相关的逻辑。跨平台支持也等同于Hosting和Avaloniaui的交集。

**Comment by textGamex** [comment]
我看那个issue上说的macos上不能用异步启动，请问你这个库解决这个问题了吗？

**Comment by NeverMorewd** [comment]
> 我看那个issue上说的macos上不能用异步启动，请问你这个库解决这个问题了吗？

没验证过，如果有mac环境可以帮测试下，感谢

**Comment by textGamex** [comment]
这样子改了之后xaml预览没法正常工作了

**Comment by NeverMorewd** [comment]
> 这样子改了之后xaml预览没法正常工作了

vm通过依赖注入进去的都会这样，需要手动设置DesignData。
可以参考：https://github.com/NeverMorewd/Lemon.ModuleNavigation/blob/89214c72159ea1abe0b360163ce7e8707bb21148/src/Lemon.ModuleNavigation.Sample/Views/MainWindow.axaml#L2

**Comment by textGamex** [comment]
xaml预览器报错
```csharp
Unhandled exception. System.InvalidOperationException: Unable to create AppBuilder from type "Moder.Core.Program". Input type either needs to have BuildAvaloniaApp -> AppBuilder method or inherit Application type.
   at Avalonia.AppBuilder.Configure(Type entryPointType)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline)
   at Avalonia.Designer.HostApp.Program.Main(String[] args)
```
